// @generated by protoc-gen-es v1.3.0 with parameter "target=ts"
// @generated from file proto/codecompa/v1/companion.proto (package codecompa.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message codecompa.v1.StreamAgentEventsRequest
 */
export class StreamAgentEventsRequest extends Message<StreamAgentEventsRequest> {
  constructor(data?: PartialMessage<StreamAgentEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.StreamAgentEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamAgentEventsRequest {
    return new StreamAgentEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamAgentEventsRequest {
    return new StreamAgentEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamAgentEventsRequest {
    return new StreamAgentEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: StreamAgentEventsRequest | PlainMessage<StreamAgentEventsRequest> | undefined, b: StreamAgentEventsRequest | PlainMessage<StreamAgentEventsRequest> | undefined): boolean {
    return proto3.util.equals(StreamAgentEventsRequest, a, b);
  }
}

/**
 * @generated from message codecompa.v1.AgentEvent
 */
export class AgentEvent extends Message<AgentEvent> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  /**
   * e.g. "COMMAND_EXECUTION_REQUEST"
   *
   * @generated from field: string type = 2;
   */
  type = "";

  /**
   * @generated from field: codecompa.v1.AgentMetadata metadata = 3;
   */
  metadata?: AgentMetadata;

  /**
   * @generated from field: codecompa.v1.AgentPayload payload = 4;
   */
  payload?: AgentPayload;

  constructor(data?: PartialMessage<AgentEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.AgentEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "metadata", kind: "message", T: AgentMetadata },
    { no: 4, name: "payload", kind: "message", T: AgentPayload },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AgentEvent {
    return new AgentEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AgentEvent {
    return new AgentEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AgentEvent {
    return new AgentEvent().fromJsonString(jsonString, options);
  }

  static equals(a: AgentEvent | PlainMessage<AgentEvent> | undefined, b: AgentEvent | PlainMessage<AgentEvent> | undefined): boolean {
    return proto3.util.equals(AgentEvent, a, b);
  }
}

/**
 * @generated from message codecompa.v1.AgentMetadata
 */
export class AgentMetadata extends Message<AgentMetadata> {
  /**
   * e.g. "VS Code"
   *
   * @generated from field: string ide = 1;
   */
  ide = "";

  /**
   * e.g. "Claude-Code-Agent"
   *
   * @generated from field: string agent_name = 2;
   */
  agentName = "";

  /**
   * @generated from field: int64 timestamp = 3;
   */
  timestamp = protoInt64.zero;

  constructor(data?: PartialMessage<AgentMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.AgentMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ide", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "agent_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AgentMetadata {
    return new AgentMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AgentMetadata {
    return new AgentMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AgentMetadata {
    return new AgentMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: AgentMetadata | PlainMessage<AgentMetadata> | undefined, b: AgentMetadata | PlainMessage<AgentMetadata> | undefined): boolean {
    return proto3.util.equals(AgentMetadata, a, b);
  }
}

/**
 * @generated from message codecompa.v1.AgentPayload
 */
export class AgentPayload extends Message<AgentPayload> {
  /**
   * @generated from field: string title = 1;
   */
  title = "";

  /**
   * @generated from field: string description = 2;
   */
  description = "";

  /**
   * @generated from field: string command = 3;
   */
  command = "";

  /**
   * @generated from field: string directory = 4;
   */
  directory = "";

  /**
   * @generated from field: string risk_level = 5;
   */
  riskLevel = "";

  /**
   * @generated from field: repeated codecompa.v1.DecisionOption options = 6;
   */
  options: DecisionOption[] = [];

  /**
   * @generated from field: bool allows_text_input = 7;
   */
  allowsTextInput = false;

  /**
   * Enriched fields for Phase 3
   *
   * Optional: Unified Git diff format
   *
   * @generated from field: string diff = 8;
   */
  diff = "";

  /**
   * Optional: Prompt or system instruction block
   *
   * @generated from field: string prompt = 9;
   */
  prompt = "";

  constructor(data?: PartialMessage<AgentPayload>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.AgentPayload";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "directory", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "risk_level", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "options", kind: "message", T: DecisionOption, repeated: true },
    { no: 7, name: "allows_text_input", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "diff", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AgentPayload {
    return new AgentPayload().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AgentPayload {
    return new AgentPayload().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AgentPayload {
    return new AgentPayload().fromJsonString(jsonString, options);
  }

  static equals(a: AgentPayload | PlainMessage<AgentPayload> | undefined, b: AgentPayload | PlainMessage<AgentPayload> | undefined): boolean {
    return proto3.util.equals(AgentPayload, a, b);
  }
}

/**
 * @generated from message codecompa.v1.DecisionOption
 */
export class DecisionOption extends Message<DecisionOption> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string label = 2;
   */
  label = "";

  constructor(data?: PartialMessage<DecisionOption>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.DecisionOption";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DecisionOption {
    return new DecisionOption().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DecisionOption {
    return new DecisionOption().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DecisionOption {
    return new DecisionOption().fromJsonString(jsonString, options);
  }

  static equals(a: DecisionOption | PlainMessage<DecisionOption> | undefined, b: DecisionOption | PlainMessage<DecisionOption> | undefined): boolean {
    return proto3.util.equals(DecisionOption, a, b);
  }
}

/**
 * @generated from message codecompa.v1.RespondToInterventionRequest
 */
export class RespondToInterventionRequest extends Message<RespondToInterventionRequest> {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId = "";

  /**
   * @generated from field: string selected_option_id = 2;
   */
  selectedOptionId = "";

  /**
   * @generated from field: string feedback_text = 3;
   */
  feedbackText = "";

  constructor(data?: PartialMessage<RespondToInterventionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.RespondToInterventionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "selected_option_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "feedback_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RespondToInterventionRequest {
    return new RespondToInterventionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RespondToInterventionRequest {
    return new RespondToInterventionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RespondToInterventionRequest {
    return new RespondToInterventionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RespondToInterventionRequest | PlainMessage<RespondToInterventionRequest> | undefined, b: RespondToInterventionRequest | PlainMessage<RespondToInterventionRequest> | undefined): boolean {
    return proto3.util.equals(RespondToInterventionRequest, a, b);
  }
}

/**
 * @generated from message codecompa.v1.RespondToInterventionResponse
 */
export class RespondToInterventionResponse extends Message<RespondToInterventionResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<RespondToInterventionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.RespondToInterventionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RespondToInterventionResponse {
    return new RespondToInterventionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RespondToInterventionResponse {
    return new RespondToInterventionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RespondToInterventionResponse {
    return new RespondToInterventionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RespondToInterventionResponse | PlainMessage<RespondToInterventionResponse> | undefined, b: RespondToInterventionResponse | PlainMessage<RespondToInterventionResponse> | undefined): boolean {
    return proto3.util.equals(RespondToInterventionResponse, a, b);
  }
}

/**
 * @generated from message codecompa.v1.RequestInterventionRequest
 */
export class RequestInterventionRequest extends Message<RequestInterventionRequest> {
  /**
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: codecompa.v1.AgentMetadata metadata = 2;
   */
  metadata?: AgentMetadata;

  /**
   * @generated from field: codecompa.v1.AgentPayload payload = 3;
   */
  payload?: AgentPayload;

  constructor(data?: PartialMessage<RequestInterventionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.RequestInterventionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "metadata", kind: "message", T: AgentMetadata },
    { no: 3, name: "payload", kind: "message", T: AgentPayload },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestInterventionRequest {
    return new RequestInterventionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestInterventionRequest {
    return new RequestInterventionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestInterventionRequest {
    return new RequestInterventionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RequestInterventionRequest | PlainMessage<RequestInterventionRequest> | undefined, b: RequestInterventionRequest | PlainMessage<RequestInterventionRequest> | undefined): boolean {
    return proto3.util.equals(RequestInterventionRequest, a, b);
  }
}

/**
 * @generated from message codecompa.v1.RequestInterventionResponse
 */
export class RequestInterventionResponse extends Message<RequestInterventionResponse> {
  /**
   * @generated from field: string selected_option_id = 1;
   */
  selectedOptionId = "";

  /**
   * @generated from field: string feedback_text = 2;
   */
  feedbackText = "";

  constructor(data?: PartialMessage<RequestInterventionResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.RequestInterventionResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "selected_option_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "feedback_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RequestInterventionResponse {
    return new RequestInterventionResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RequestInterventionResponse {
    return new RequestInterventionResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RequestInterventionResponse {
    return new RequestInterventionResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RequestInterventionResponse | PlainMessage<RequestInterventionResponse> | undefined, b: RequestInterventionResponse | PlainMessage<RequestInterventionResponse> | undefined): boolean {
    return proto3.util.equals(RequestInterventionResponse, a, b);
  }
}

/**
 * @generated from message codecompa.v1.PostTelemetryEventRequest
 */
export class PostTelemetryEventRequest extends Message<PostTelemetryEventRequest> {
  /**
   * e.g. "TERMINAL_COMMAND_STARTED", "FILE_CREATED"
   *
   * @generated from field: string type = 1;
   */
  type = "";

  /**
   * @generated from field: codecompa.v1.AgentMetadata metadata = 2;
   */
  metadata?: AgentMetadata;

  /**
   * @generated from field: string title = 3;
   */
  title = "";

  /**
   * @generated from field: string description = 4;
   */
  description = "";

  /**
   * Extra dynamic properties
   *
   * @generated from field: string payload_json = 5;
   */
  payloadJson = "";

  constructor(data?: PartialMessage<PostTelemetryEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.PostTelemetryEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "metadata", kind: "message", T: AgentMetadata },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "payload_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PostTelemetryEventRequest {
    return new PostTelemetryEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PostTelemetryEventRequest {
    return new PostTelemetryEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PostTelemetryEventRequest {
    return new PostTelemetryEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PostTelemetryEventRequest | PlainMessage<PostTelemetryEventRequest> | undefined, b: PostTelemetryEventRequest | PlainMessage<PostTelemetryEventRequest> | undefined): boolean {
    return proto3.util.equals(PostTelemetryEventRequest, a, b);
  }
}

/**
 * @generated from message codecompa.v1.PostTelemetryEventResponse
 */
export class PostTelemetryEventResponse extends Message<PostTelemetryEventResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<PostTelemetryEventResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "codecompa.v1.PostTelemetryEventResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PostTelemetryEventResponse {
    return new PostTelemetryEventResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PostTelemetryEventResponse {
    return new PostTelemetryEventResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PostTelemetryEventResponse {
    return new PostTelemetryEventResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PostTelemetryEventResponse | PlainMessage<PostTelemetryEventResponse> | undefined, b: PostTelemetryEventResponse | PlainMessage<PostTelemetryEventResponse> | undefined): boolean {
    return proto3.util.equals(PostTelemetryEventResponse, a, b);
  }
}

