// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file proto/codecompa/v1/companion.proto (package codecompa.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AgentEvent, RequestInterventionRequest, RequestInterventionResponse, RespondToInterventionRequest, RespondToInterventionResponse, StreamAgentEventsRequest } from "./companion_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service codecompa.v1.CompanionService
 */
export const CompanionService = {
  typeName: "codecompa.v1.CompanionService",
  methods: {
    /**
     * The mobile app calls this stream to receive real-time events from the AI agent
     *
     * @generated from rpc codecompa.v1.CompanionService.StreamAgentEvents
     */
    streamAgentEvents: {
      name: "StreamAgentEvents",
      I: StreamAgentEventsRequest,
      O: AgentEvent,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * The mobile app responds to a pending human intervention request
     *
     * @generated from rpc codecompa.v1.CompanionService.RespondToIntervention
     */
    respondToIntervention: {
      name: "RespondToIntervention",
      I: RespondToInterventionRequest,
      O: RespondToInterventionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * The IDE extension (or local agent) calls this to request human intervention and wait for the response
     *
     * @generated from rpc codecompa.v1.CompanionService.RequestIntervention
     */
    requestIntervention: {
      name: "RequestIntervention",
      I: RequestInterventionRequest,
      O: RequestInterventionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

