"use strict";
// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file proto/codecompa/v1/companion.proto (package codecompa.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.CompanionService = void 0;
const companion_pb_js_1 = require("./companion_pb.js");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service codecompa.v1.CompanionService
 */
exports.CompanionService = {
    typeName: "codecompa.v1.CompanionService",
    methods: {
        /**
         * The mobile app calls this stream to receive real-time events from the AI agent
         *
         * @generated from rpc codecompa.v1.CompanionService.StreamAgentEvents
         */
        streamAgentEvents: {
            name: "StreamAgentEvents",
            I: companion_pb_js_1.StreamAgentEventsRequest,
            O: companion_pb_js_1.AgentEvent,
            kind: protobuf_1.MethodKind.ServerStreaming,
        },
        /**
         * The mobile app responds to a pending human intervention request
         *
         * @generated from rpc codecompa.v1.CompanionService.RespondToIntervention
         */
        respondToIntervention: {
            name: "RespondToIntervention",
            I: companion_pb_js_1.RespondToInterventionRequest,
            O: companion_pb_js_1.RespondToInterventionResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * The IDE extension (or local agent) calls this to request human intervention and wait for the response
         *
         * @generated from rpc codecompa.v1.CompanionService.RequestIntervention
         */
        requestIntervention: {
            name: "RequestIntervention",
            I: companion_pb_js_1.RequestInterventionRequest,
            O: companion_pb_js_1.RequestInterventionResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
//# sourceMappingURL=companion_connect.js.map