"use strict";
// @generated by protoc-gen-es v1.3.0 with parameter "target=ts"
// @generated from file proto/codecompa/v1/companion.proto (package codecompa.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestInterventionResponse = exports.RequestInterventionRequest = exports.RespondToInterventionResponse = exports.RespondToInterventionRequest = exports.DecisionOption = exports.AgentPayload = exports.AgentMetadata = exports.AgentEvent = exports.StreamAgentEventsRequest = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from message codecompa.v1.StreamAgentEventsRequest
 */
class StreamAgentEventsRequest extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.StreamAgentEventsRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => []);
    static fromBinary(bytes, options) {
        return new StreamAgentEventsRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new StreamAgentEventsRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new StreamAgentEventsRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(StreamAgentEventsRequest, a, b);
    }
}
exports.StreamAgentEventsRequest = StreamAgentEventsRequest;
/**
 * @generated from message codecompa.v1.AgentEvent
 */
class AgentEvent extends protobuf_1.Message {
    /**
     * @generated from field: string event_id = 1;
     */
    eventId = "";
    /**
     * e.g. "COMMAND_EXECUTION_REQUEST"
     *
     * @generated from field: string type = 2;
     */
    type = "";
    /**
     * @generated from field: codecompa.v1.AgentMetadata metadata = 3;
     */
    metadata;
    /**
     * @generated from field: codecompa.v1.AgentPayload payload = 4;
     */
    payload;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.AgentEvent";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "metadata", kind: "message", T: AgentMetadata },
        { no: 4, name: "payload", kind: "message", T: AgentPayload },
    ]);
    static fromBinary(bytes, options) {
        return new AgentEvent().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AgentEvent().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AgentEvent().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AgentEvent, a, b);
    }
}
exports.AgentEvent = AgentEvent;
/**
 * @generated from message codecompa.v1.AgentMetadata
 */
class AgentMetadata extends protobuf_1.Message {
    /**
     * e.g. "VS Code"
     *
     * @generated from field: string ide = 1;
     */
    ide = "";
    /**
     * e.g. "Claude-Code-Agent"
     *
     * @generated from field: string agent_name = 2;
     */
    agentName = "";
    /**
     * @generated from field: int64 timestamp = 3;
     */
    timestamp = protobuf_1.protoInt64.zero;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.AgentMetadata";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "ide", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "agent_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "timestamp", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    ]);
    static fromBinary(bytes, options) {
        return new AgentMetadata().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AgentMetadata().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AgentMetadata().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AgentMetadata, a, b);
    }
}
exports.AgentMetadata = AgentMetadata;
/**
 * @generated from message codecompa.v1.AgentPayload
 */
class AgentPayload extends protobuf_1.Message {
    /**
     * @generated from field: string title = 1;
     */
    title = "";
    /**
     * @generated from field: string description = 2;
     */
    description = "";
    /**
     * @generated from field: string command = 3;
     */
    command = "";
    /**
     * @generated from field: string directory = 4;
     */
    directory = "";
    /**
     * @generated from field: string risk_level = 5;
     */
    riskLevel = "";
    /**
     * @generated from field: repeated codecompa.v1.DecisionOption options = 6;
     */
    options = [];
    /**
     * @generated from field: bool allows_text_input = 7;
     */
    allowsTextInput = false;
    /**
     * Enriched fields for Phase 3
     *
     * Optional: Unified Git diff format
     *
     * @generated from field: string diff = 8;
     */
    diff = "";
    /**
     * Optional: Prompt or system instruction block
     *
     * @generated from field: string prompt = 9;
     */
    prompt = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.AgentPayload";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "directory", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "risk_level", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 6, name: "options", kind: "message", T: DecisionOption, repeated: true },
        { no: 7, name: "allows_text_input", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 8, name: "diff", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 9, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new AgentPayload().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AgentPayload().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AgentPayload().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AgentPayload, a, b);
    }
}
exports.AgentPayload = AgentPayload;
/**
 * @generated from message codecompa.v1.DecisionOption
 */
class DecisionOption extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    /**
     * @generated from field: string label = 2;
     */
    label = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.DecisionOption";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new DecisionOption().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DecisionOption().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DecisionOption().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DecisionOption, a, b);
    }
}
exports.DecisionOption = DecisionOption;
/**
 * @generated from message codecompa.v1.RespondToInterventionRequest
 */
class RespondToInterventionRequest extends protobuf_1.Message {
    /**
     * @generated from field: string event_id = 1;
     */
    eventId = "";
    /**
     * @generated from field: string selected_option_id = 2;
     */
    selectedOptionId = "";
    /**
     * @generated from field: string feedback_text = 3;
     */
    feedbackText = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.RespondToInterventionRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "selected_option_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "feedback_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new RespondToInterventionRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RespondToInterventionRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RespondToInterventionRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RespondToInterventionRequest, a, b);
    }
}
exports.RespondToInterventionRequest = RespondToInterventionRequest;
/**
 * @generated from message codecompa.v1.RespondToInterventionResponse
 */
class RespondToInterventionResponse extends protobuf_1.Message {
    /**
     * @generated from field: bool success = 1;
     */
    success = false;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.RespondToInterventionResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    ]);
    static fromBinary(bytes, options) {
        return new RespondToInterventionResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RespondToInterventionResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RespondToInterventionResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RespondToInterventionResponse, a, b);
    }
}
exports.RespondToInterventionResponse = RespondToInterventionResponse;
/**
 * @generated from message codecompa.v1.RequestInterventionRequest
 */
class RequestInterventionRequest extends protobuf_1.Message {
    /**
     * @generated from field: string type = 1;
     */
    type = "";
    /**
     * @generated from field: codecompa.v1.AgentMetadata metadata = 2;
     */
    metadata;
    /**
     * @generated from field: codecompa.v1.AgentPayload payload = 3;
     */
    payload;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.RequestInterventionRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "metadata", kind: "message", T: AgentMetadata },
        { no: 3, name: "payload", kind: "message", T: AgentPayload },
    ]);
    static fromBinary(bytes, options) {
        return new RequestInterventionRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RequestInterventionRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RequestInterventionRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RequestInterventionRequest, a, b);
    }
}
exports.RequestInterventionRequest = RequestInterventionRequest;
/**
 * @generated from message codecompa.v1.RequestInterventionResponse
 */
class RequestInterventionResponse extends protobuf_1.Message {
    /**
     * @generated from field: string selected_option_id = 1;
     */
    selectedOptionId = "";
    /**
     * @generated from field: string feedback_text = 2;
     */
    feedbackText = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "codecompa.v1.RequestInterventionResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "selected_option_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "feedback_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new RequestInterventionResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RequestInterventionResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RequestInterventionResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RequestInterventionResponse, a, b);
    }
}
exports.RequestInterventionResponse = RequestInterventionResponse;
//# sourceMappingURL=companion_pb.js.map