// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: proto/codecompa/v1/companion.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamAgentEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamAgentEventsRequest) Reset() {
	*x = StreamAgentEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamAgentEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAgentEventsRequest) ProtoMessage() {}

func (x *StreamAgentEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAgentEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamAgentEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{0}
}

type AgentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId  string         `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type     string         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // e.g. "COMMAND_EXECUTION_REQUEST"
	Metadata *AgentMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Payload  *AgentPayload  `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AgentEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentEvent) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentEvent) GetPayload() *AgentPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AgentMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ide       string `protobuf:"bytes,1,opt,name=ide,proto3" json:"ide,omitempty"`                              // e.g. "VS Code"
	AgentName string `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"` // e.g. "Claude-Code-Agent"
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *AgentMetadata) Reset() {
	*x = AgentMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetadata) ProtoMessage() {}

func (x *AgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetadata.ProtoReflect.Descriptor instead.
func (*AgentMetadata) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMetadata) GetIde() string {
	if x != nil {
		return x.Ide
	}
	return ""
}

func (x *AgentMetadata) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AgentPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title           string            `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string            `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Command         string            `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Directory       string            `protobuf:"bytes,4,opt,name=directory,proto3" json:"directory,omitempty"`
	RiskLevel       string            `protobuf:"bytes,5,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Options         []*DecisionOption `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	AllowsTextInput bool              `protobuf:"varint,7,opt,name=allows_text_input,json=allowsTextInput,proto3" json:"allows_text_input,omitempty"`
	// Enriched fields for Phase 3
	Diff   string `protobuf:"bytes,8,opt,name=diff,proto3" json:"diff,omitempty"`     // Optional: Unified Git diff format
	Prompt string `protobuf:"bytes,9,opt,name=prompt,proto3" json:"prompt,omitempty"` // Optional: Prompt or system instruction block
}

func (x *AgentPayload) Reset() {
	*x = AgentPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPayload) ProtoMessage() {}

func (x *AgentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPayload.ProtoReflect.Descriptor instead.
func (*AgentPayload) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{3}
}

func (x *AgentPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AgentPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentPayload) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *AgentPayload) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *AgentPayload) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *AgentPayload) GetOptions() []*DecisionOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *AgentPayload) GetAllowsTextInput() bool {
	if x != nil {
		return x.AllowsTextInput
	}
	return false
}

func (x *AgentPayload) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *AgentPayload) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type DecisionOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *DecisionOption) Reset() {
	*x = DecisionOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionOption) ProtoMessage() {}

func (x *DecisionOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionOption.ProtoReflect.Descriptor instead.
func (*DecisionOption) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DecisionOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type RespondToInterventionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId          string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SelectedOptionId string `protobuf:"bytes,2,opt,name=selected_option_id,json=selectedOptionId,proto3" json:"selected_option_id,omitempty"`
	FeedbackText     string `protobuf:"bytes,3,opt,name=feedback_text,json=feedbackText,proto3" json:"feedback_text,omitempty"`
}

func (x *RespondToInterventionRequest) Reset() {
	*x = RespondToInterventionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespondToInterventionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInterventionRequest) ProtoMessage() {}

func (x *RespondToInterventionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInterventionRequest.ProtoReflect.Descriptor instead.
func (*RespondToInterventionRequest) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{5}
}

func (x *RespondToInterventionRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RespondToInterventionRequest) GetSelectedOptionId() string {
	if x != nil {
		return x.SelectedOptionId
	}
	return ""
}

func (x *RespondToInterventionRequest) GetFeedbackText() string {
	if x != nil {
		return x.FeedbackText
	}
	return ""
}

type RespondToInterventionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RespondToInterventionResponse) Reset() {
	*x = RespondToInterventionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespondToInterventionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInterventionResponse) ProtoMessage() {}

func (x *RespondToInterventionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInterventionResponse.ProtoReflect.Descriptor instead.
func (*RespondToInterventionResponse) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{6}
}

func (x *RespondToInterventionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RequestInterventionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Metadata *AgentMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Payload  *AgentPayload  `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *RequestInterventionRequest) Reset() {
	*x = RequestInterventionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInterventionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInterventionRequest) ProtoMessage() {}

func (x *RequestInterventionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInterventionRequest.ProtoReflect.Descriptor instead.
func (*RequestInterventionRequest) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{7}
}

func (x *RequestInterventionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RequestInterventionRequest) GetMetadata() *AgentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RequestInterventionRequest) GetPayload() *AgentPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RequestInterventionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelectedOptionId string `protobuf:"bytes,1,opt,name=selected_option_id,json=selectedOptionId,proto3" json:"selected_option_id,omitempty"`
	FeedbackText     string `protobuf:"bytes,2,opt,name=feedback_text,json=feedbackText,proto3" json:"feedback_text,omitempty"`
}

func (x *RequestInterventionResponse) Reset() {
	*x = RequestInterventionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_codecompa_v1_companion_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestInterventionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInterventionResponse) ProtoMessage() {}

func (x *RequestInterventionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_codecompa_v1_companion_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInterventionResponse.ProtoReflect.Descriptor instead.
func (*RequestInterventionResponse) Descriptor() ([]byte, []int) {
	return file_proto_codecompa_v1_companion_proto_rawDescGZIP(), []int{8}
}

func (x *RequestInterventionResponse) GetSelectedOptionId() string {
	if x != nil {
		return x.SelectedOptionId
	}
	return ""
}

func (x *RequestInterventionResponse) GetFeedbackText() string {
	if x != nil {
		return x.FeedbackText
	}
	return ""
}

var File_proto_codecompa_v1_companion_proto protoreflect.FileDescriptor

var file_proto_codecompa_v1_companion_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2e,
	0x76, 0x31, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xaa,
	0x01, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5e, 0x0a, 0x0d, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xad, 0x02, 0x0a, 0x0c,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x69, 0x73, 0x6b, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x69, 0x73, 0x6b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x36, 0x0a, 0x07, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63,
	0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x5f, 0x74, 0x65,
	0x78, 0x74, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x54, 0x65, 0x78, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x69, 0x66, 0x66, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x69, 0x66, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0x36, 0x0a, 0x0e, 0x44,
	0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x22, 0x8c, 0x01, 0x0a, 0x1c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x54,
	0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x12, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x65,
	0x78, 0x74, 0x22, 0x39, 0x0a, 0x1d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x54, 0x6f, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x9f, 0x01,
	0x0a, 0x1a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x37, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x64,
	0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x70, 0x0a, 0x1b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c,
	0x0a, 0x12, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x65, 0x78,
	0x74, 0x32, 0xc9, 0x02, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x2e, 0x63, 0x6f,
	0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x12,
	0x70, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x54, 0x6f, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x54,
	0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x54, 0x6f, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6a, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x65,
	0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x58, 0x5a,
	0x56, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x6c, 0x62,
	0x61, 0x72, 0x72, 0x61, 0x6e, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x2f, 0x76,
	0x31, 0x3b, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_codecompa_v1_companion_proto_rawDescOnce sync.Once
	file_proto_codecompa_v1_companion_proto_rawDescData = file_proto_codecompa_v1_companion_proto_rawDesc
)

func file_proto_codecompa_v1_companion_proto_rawDescGZIP() []byte {
	file_proto_codecompa_v1_companion_proto_rawDescOnce.Do(func() {
		file_proto_codecompa_v1_companion_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_codecompa_v1_companion_proto_rawDescData)
	})
	return file_proto_codecompa_v1_companion_proto_rawDescData
}

var file_proto_codecompa_v1_companion_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_codecompa_v1_companion_proto_goTypes = []interface{}{
	(*StreamAgentEventsRequest)(nil),      // 0: codecompa.v1.StreamAgentEventsRequest
	(*AgentEvent)(nil),                    // 1: codecompa.v1.AgentEvent
	(*AgentMetadata)(nil),                 // 2: codecompa.v1.AgentMetadata
	(*AgentPayload)(nil),                  // 3: codecompa.v1.AgentPayload
	(*DecisionOption)(nil),                // 4: codecompa.v1.DecisionOption
	(*RespondToInterventionRequest)(nil),  // 5: codecompa.v1.RespondToInterventionRequest
	(*RespondToInterventionResponse)(nil), // 6: codecompa.v1.RespondToInterventionResponse
	(*RequestInterventionRequest)(nil),    // 7: codecompa.v1.RequestInterventionRequest
	(*RequestInterventionResponse)(nil),   // 8: codecompa.v1.RequestInterventionResponse
}
var file_proto_codecompa_v1_companion_proto_depIdxs = []int32{
	2, // 0: codecompa.v1.AgentEvent.metadata:type_name -> codecompa.v1.AgentMetadata
	3, // 1: codecompa.v1.AgentEvent.payload:type_name -> codecompa.v1.AgentPayload
	4, // 2: codecompa.v1.AgentPayload.options:type_name -> codecompa.v1.DecisionOption
	2, // 3: codecompa.v1.RequestInterventionRequest.metadata:type_name -> codecompa.v1.AgentMetadata
	3, // 4: codecompa.v1.RequestInterventionRequest.payload:type_name -> codecompa.v1.AgentPayload
	0, // 5: codecompa.v1.CompanionService.StreamAgentEvents:input_type -> codecompa.v1.StreamAgentEventsRequest
	5, // 6: codecompa.v1.CompanionService.RespondToIntervention:input_type -> codecompa.v1.RespondToInterventionRequest
	7, // 7: codecompa.v1.CompanionService.RequestIntervention:input_type -> codecompa.v1.RequestInterventionRequest
	1, // 8: codecompa.v1.CompanionService.StreamAgentEvents:output_type -> codecompa.v1.AgentEvent
	6, // 9: codecompa.v1.CompanionService.RespondToIntervention:output_type -> codecompa.v1.RespondToInterventionResponse
	8, // 10: codecompa.v1.CompanionService.RequestIntervention:output_type -> codecompa.v1.RequestInterventionResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_codecompa_v1_companion_proto_init() }
func file_proto_codecompa_v1_companion_proto_init() {
	if File_proto_codecompa_v1_companion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_codecompa_v1_companion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamAgentEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codecompa_v1_companion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codecompa_v1_companion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codecompa_v1_companion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codecompa_v1_companion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecisionOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codecompa_v1_companion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespondToInterventionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codecompa_v1_companion_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespondToInterventionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codecompa_v1_companion_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInterventionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_codecompa_v1_companion_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestInterventionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_codecompa_v1_companion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_codecompa_v1_companion_proto_goTypes,
		DependencyIndexes: file_proto_codecompa_v1_companion_proto_depIdxs,
		MessageInfos:      file_proto_codecompa_v1_companion_proto_msgTypes,
	}.Build()
	File_proto_codecompa_v1_companion_proto = out.File
	file_proto_codecompa_v1_companion_proto_rawDesc = nil
	file_proto_codecompa_v1_companion_proto_goTypes = nil
	file_proto_codecompa_v1_companion_proto_depIdxs = nil
}
