// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/codecompa/v1/companion.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/jalbarran/code-compa/packages/bridge-go/pkg/api/v1/proto/codecompa/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// CompanionServiceName is the fully-qualified name of the CompanionService service.
	CompanionServiceName = "codecompa.v1.CompanionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CompanionServiceStreamAgentEventsProcedure is the fully-qualified name of the CompanionService's
	// StreamAgentEvents RPC.
	CompanionServiceStreamAgentEventsProcedure = "/codecompa.v1.CompanionService/StreamAgentEvents"
	// CompanionServiceRespondToInterventionProcedure is the fully-qualified name of the
	// CompanionService's RespondToIntervention RPC.
	CompanionServiceRespondToInterventionProcedure = "/codecompa.v1.CompanionService/RespondToIntervention"
	// CompanionServiceRequestInterventionProcedure is the fully-qualified name of the
	// CompanionService's RequestIntervention RPC.
	CompanionServiceRequestInterventionProcedure = "/codecompa.v1.CompanionService/RequestIntervention"
	// CompanionServicePostTelemetryEventProcedure is the fully-qualified name of the CompanionService's
	// PostTelemetryEvent RPC.
	CompanionServicePostTelemetryEventProcedure = "/codecompa.v1.CompanionService/PostTelemetryEvent"
)

// CompanionServiceClient is a client for the codecompa.v1.CompanionService service.
type CompanionServiceClient interface {
	// The mobile app calls this stream to receive real-time events from the AI agent
	StreamAgentEvents(context.Context, *connect.Request[v1.StreamAgentEventsRequest]) (*connect.ServerStreamForClient[v1.AgentEvent], error)
	// The mobile app responds to a pending human intervention request
	RespondToIntervention(context.Context, *connect.Request[v1.RespondToInterventionRequest]) (*connect.Response[v1.RespondToInterventionResponse], error)
	// The IDE extension (or local agent) calls this to request human intervention and wait for the response
	RequestIntervention(context.Context, *connect.Request[v1.RequestInterventionRequest]) (*connect.Response[v1.RequestInterventionResponse], error)
	// The IDE extension (or local agent) calls this to post non-blocking telemetry and log updates
	PostTelemetryEvent(context.Context, *connect.Request[v1.PostTelemetryEventRequest]) (*connect.Response[v1.PostTelemetryEventResponse], error)
}

// NewCompanionServiceClient constructs a client for the codecompa.v1.CompanionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCompanionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CompanionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &companionServiceClient{
		streamAgentEvents: connect.NewClient[v1.StreamAgentEventsRequest, v1.AgentEvent](
			httpClient,
			baseURL+CompanionServiceStreamAgentEventsProcedure,
			opts...,
		),
		respondToIntervention: connect.NewClient[v1.RespondToInterventionRequest, v1.RespondToInterventionResponse](
			httpClient,
			baseURL+CompanionServiceRespondToInterventionProcedure,
			opts...,
		),
		requestIntervention: connect.NewClient[v1.RequestInterventionRequest, v1.RequestInterventionResponse](
			httpClient,
			baseURL+CompanionServiceRequestInterventionProcedure,
			opts...,
		),
		postTelemetryEvent: connect.NewClient[v1.PostTelemetryEventRequest, v1.PostTelemetryEventResponse](
			httpClient,
			baseURL+CompanionServicePostTelemetryEventProcedure,
			opts...,
		),
	}
}

// companionServiceClient implements CompanionServiceClient.
type companionServiceClient struct {
	streamAgentEvents     *connect.Client[v1.StreamAgentEventsRequest, v1.AgentEvent]
	respondToIntervention *connect.Client[v1.RespondToInterventionRequest, v1.RespondToInterventionResponse]
	requestIntervention   *connect.Client[v1.RequestInterventionRequest, v1.RequestInterventionResponse]
	postTelemetryEvent    *connect.Client[v1.PostTelemetryEventRequest, v1.PostTelemetryEventResponse]
}

// StreamAgentEvents calls codecompa.v1.CompanionService.StreamAgentEvents.
func (c *companionServiceClient) StreamAgentEvents(ctx context.Context, req *connect.Request[v1.StreamAgentEventsRequest]) (*connect.ServerStreamForClient[v1.AgentEvent], error) {
	return c.streamAgentEvents.CallServerStream(ctx, req)
}

// RespondToIntervention calls codecompa.v1.CompanionService.RespondToIntervention.
func (c *companionServiceClient) RespondToIntervention(ctx context.Context, req *connect.Request[v1.RespondToInterventionRequest]) (*connect.Response[v1.RespondToInterventionResponse], error) {
	return c.respondToIntervention.CallUnary(ctx, req)
}

// RequestIntervention calls codecompa.v1.CompanionService.RequestIntervention.
func (c *companionServiceClient) RequestIntervention(ctx context.Context, req *connect.Request[v1.RequestInterventionRequest]) (*connect.Response[v1.RequestInterventionResponse], error) {
	return c.requestIntervention.CallUnary(ctx, req)
}

// PostTelemetryEvent calls codecompa.v1.CompanionService.PostTelemetryEvent.
func (c *companionServiceClient) PostTelemetryEvent(ctx context.Context, req *connect.Request[v1.PostTelemetryEventRequest]) (*connect.Response[v1.PostTelemetryEventResponse], error) {
	return c.postTelemetryEvent.CallUnary(ctx, req)
}

// CompanionServiceHandler is an implementation of the codecompa.v1.CompanionService service.
type CompanionServiceHandler interface {
	// The mobile app calls this stream to receive real-time events from the AI agent
	StreamAgentEvents(context.Context, *connect.Request[v1.StreamAgentEventsRequest], *connect.ServerStream[v1.AgentEvent]) error
	// The mobile app responds to a pending human intervention request
	RespondToIntervention(context.Context, *connect.Request[v1.RespondToInterventionRequest]) (*connect.Response[v1.RespondToInterventionResponse], error)
	// The IDE extension (or local agent) calls this to request human intervention and wait for the response
	RequestIntervention(context.Context, *connect.Request[v1.RequestInterventionRequest]) (*connect.Response[v1.RequestInterventionResponse], error)
	// The IDE extension (or local agent) calls this to post non-blocking telemetry and log updates
	PostTelemetryEvent(context.Context, *connect.Request[v1.PostTelemetryEventRequest]) (*connect.Response[v1.PostTelemetryEventResponse], error)
}

// NewCompanionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCompanionServiceHandler(svc CompanionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	companionServiceStreamAgentEventsHandler := connect.NewServerStreamHandler(
		CompanionServiceStreamAgentEventsProcedure,
		svc.StreamAgentEvents,
		opts...,
	)
	companionServiceRespondToInterventionHandler := connect.NewUnaryHandler(
		CompanionServiceRespondToInterventionProcedure,
		svc.RespondToIntervention,
		opts...,
	)
	companionServiceRequestInterventionHandler := connect.NewUnaryHandler(
		CompanionServiceRequestInterventionProcedure,
		svc.RequestIntervention,
		opts...,
	)
	companionServicePostTelemetryEventHandler := connect.NewUnaryHandler(
		CompanionServicePostTelemetryEventProcedure,
		svc.PostTelemetryEvent,
		opts...,
	)
	return "/codecompa.v1.CompanionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CompanionServiceStreamAgentEventsProcedure:
			companionServiceStreamAgentEventsHandler.ServeHTTP(w, r)
		case CompanionServiceRespondToInterventionProcedure:
			companionServiceRespondToInterventionHandler.ServeHTTP(w, r)
		case CompanionServiceRequestInterventionProcedure:
			companionServiceRequestInterventionHandler.ServeHTTP(w, r)
		case CompanionServicePostTelemetryEventProcedure:
			companionServicePostTelemetryEventHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCompanionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCompanionServiceHandler struct{}

func (UnimplementedCompanionServiceHandler) StreamAgentEvents(context.Context, *connect.Request[v1.StreamAgentEventsRequest], *connect.ServerStream[v1.AgentEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("codecompa.v1.CompanionService.StreamAgentEvents is not implemented"))
}

func (UnimplementedCompanionServiceHandler) RespondToIntervention(context.Context, *connect.Request[v1.RespondToInterventionRequest]) (*connect.Response[v1.RespondToInterventionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codecompa.v1.CompanionService.RespondToIntervention is not implemented"))
}

func (UnimplementedCompanionServiceHandler) RequestIntervention(context.Context, *connect.Request[v1.RequestInterventionRequest]) (*connect.Response[v1.RequestInterventionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codecompa.v1.CompanionService.RequestIntervention is not implemented"))
}

func (UnimplementedCompanionServiceHandler) PostTelemetryEvent(context.Context, *connect.Request[v1.PostTelemetryEventRequest]) (*connect.Response[v1.PostTelemetryEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("codecompa.v1.CompanionService.PostTelemetryEvent is not implemented"))
}
